### PR TITLE
Update minimum supported TLS version to 1.2.

### PR DESCRIPTION
**Pull request by notdurson**

### CODE REVIEW

**Comment by rg0now** [comment]
Thanks, looks reasonable.

Can we get away without a code-owners file, is it some sort of a requirement on your side? We will ask you to collapse your patches into a single commit so that we can merge clearly, i.e., your identity will be there forever in the git tree, isn't that enough?

**Comment by notdurson** [comment]
Yes sorry, I will remove the codeowners file (it was intended for our
internal fork).

**Comment by notdurson** [comment]
@rg0now deleted. Can you check again pls?

**Comment by rg0now** [comment]
Very nice, thanks. Last request: can you collapse the whole thing into a single commit? I think if I squash-merge you lose your authorship (is that true?), but if I merge as is we mess up the git history with lots of useless commits. Wdyt?

**Comment by notdurson** [comment]
Gabor, I can - I'm going to open a new PR though, because my local commit log is messed up.

**Pull request closed without merging**
