### PR TITLE
Rtd

### PR DESCRIPTION
**Pull request by VidarHUN**
https://stunner.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by davidkornel** [comment]
I started to use it and on [the gateway page](https://stunner.readthedocs.io/en/latest/GATEWAY/), the gateway hierarchy figure does not show up for me

**Comment by levaitamas** [comment]
Thanks, this looks neat! One question though. Any idea why are the  _Examples_ always 'open' (as shown in this pic)?


image

**Comment by VidarHUN** [comment]
I think this happening because of the multiple subdirectories, but I can't find mkdocs config to fix this.

**Comment by rg0now** [comment]
Guys, this is truly amazing, thanks!  I'm OK with merging this right away, wdyt?

**Comment by VidarHUN** [comment]
Please wait for today.

**Comment by VidarHUN** [comment]
Navbar fixed and favicon added. Now is ready to merge.
https://stunner.readthedocs.io/en/latest/

**Comment by levaitamas** [comment]
Awesome, great work! Thanks a lot!

**Pull request merged**
